server:
  port: 8084

spring:
  application:
    name: account-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-vkxlfm4oy207h5bq.us.auth0.com/

customer:
  service:
    url: http://customer-service:8083

auth0:
  audience: https://mockbank/api

logging:
  level:
    org.springframework.security.oauth2.jwt: TRACE
    org.springframework.security.oauth2.server.resource.authentication: TRACE
    org.springframework.security: INFO
