server:
  port: 8088

spring:
  application:
    name: biller-service

  datasource:
    url: jdbc:postgresql://localhost:5432/billerdb?options=-c%20TimeZone=UTC
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-vkxlfm4oy207h5bq.us.auth0.com/

auth0:
  audience: https://mockbank/api

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
