server:
  port: 8090

spring:
  application:
    name: billpay-worker-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${BILLPAY_WORKER_CONSUMER_GROUP:billpay-worker-v1}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-wgk04dj5v68sbhre.us.auth0.com/

payments:
  topics:
    billpay-requested: billpay.requested
    billpay-enqueued: billpay.enqueued
    bill-batch-ready: bill.batch.ready
  batch:
    threshold: 1

auth0:
  audience: https://mockbank/api

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
