server:
  port: 8088

spring:
  application:
    name: biller-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-wgk04dj5v68sbhre.us.auth0.com/

auth0:
  audience: https://mockbank/api

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security: DEBUG
