global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: spring-boot-actuator

    metrics_path: /actuator/prometheus

    static_configs:
      - targets:
          - host.docker.internal:8080   # api-gateway
          - host.docker.internal:8083   # customer-service
          - host.docker.internal:8084   # account-service
          - host.docker.internal:8086   # payment-orchestrator
          - host.docker.internal:8087   # settlement-service
          - host.docker.internal:8088   # biller-service
          - host.docker.internal:8090   # billpay-worker-service
          - host.docker.internal:8094   # auth-user

    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

        