spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-vkxlfm4oy207h5bq.us.auth0.com/}