spring:
  profiles:
    active: dev

  application:
    name: customer-service

  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG